### ISSUE TITLE
Generator does not detect inside-namespace imports

### ISSUE THREAD

**Issue by thaumanovic** [BlackWhiteYoshi/AutoInterface#1]
When using `using` declarations *within* a namespace block, the generator does not generate imports in its output. 

I would expect the following code:
```cs
namespace Thaum.Gw2Api.Clients
{
    using System.Threading;
    using System.Threading.Tasks;
    using AutoInterfaceAttributes;
    using Thaum.Gw2Api.Models;
    
    [AutoInterface]
    public sealed class Gw2AccountApi : IGw2AccountApi
    {
```
To identify and maintain the imports within the namespace block, like so:
```cs
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace Thaum.Gw2Api.Clients
{
    using System.Threading;
    using System.Threading.Tasks;
    using AutoInterfaceAttributes;
    using Thaum.Gw2Api.Models;

    public interface IGw2AccountApi
    {
        Task<Account?> GetAccountInfo(string apiKey, CancellationToken ct);
    }
}
```
But it in fact generates the following, causing errors in my code (that the interface is not implemented):
```cs
// <auto-generated/>
#pragma warning disable
#nullable enable annotations


namespace Thaum.Gw2Api.Clients;

public interface IGw2AccountApi {
    Task<Account?> GetAccountInfo(string apiKey, CancellationToken ct);
}
```

**Comment by BlackWhiteYoshi** [comment]
I did not consider the possibility for nested *namespaces* or nested *using* statements, thank you for pointing this out. I fixed it in the newest version.  
But be aware that only fully-qualified *using* statements will work. In your case you could also write your *using* statement with just "Models":

```csharp
namespace Thaum.Gw2Api.Clients
{
    using System.Threading;
    using System.Threading.Tasks;
    using AutoInterfaceAttributes;
    using Models; // refers to "Thaum.Gw2Api.Models", but generated code will refer to just "Models"

    [AutoInterface]
    public sealed class Gw2AccountApi : IGw2AccountApi
    {

```
But not fully-qualified *using* statements are dangerous, because they can be ambiguous. For example if you create somewhere in your project the *namespace* “Thaum.Gw2Api.Clients.Models”, all your nested “Models” *usings* inside the “Thaum.Gw2Api.Clients” *namespace* will suddenly refer to “Thaum.Gw2Api.Clients.Models” and you get compile errors all over the place. That’s why usually *using* statements are always full qualified and put at the top of a file.

I also left a note in README.md: [#remark](https://github.com/BlackWhiteYoshi/AutoInterface#remarks)

**Comment by thaumanovic** [comment]
Thanks for the quick fix!

I'm aware of the caveats with using *using* declarations within a namespace, it's bitten me before - so I do keep them fully-qualified, I just prefer the structure of having them within the namespace because of other languages I've worked with, so I don't foresee any issues for me.

I do need more source-generator experience, so I *may* in the near future submit a PR to handle both cases (i.e. generate output to match the structure of inputs), if you'd accept one?

Thanks again!
