### ISSUE TITLE
Feature 'file-scoped namespaces' is not available. Please use language version 10.0 or greater.

### ISSUE THREAD

**Issue by thaumanovic** [BlackWhiteYoshi/AutoInterface#10]
We'd like to use `AutoInterface` in an API client SDK which we're targeting to `netstandard2.1`

Unfortunately, it seems that `AutoInterface` generates types with file-scoped namespaces. This is unsupported in C# 8.0, which is the highest language version that is supported by .NET Standard 2.1.

Can we generate the interfaces in a namespace block to mitigate this issue?

**Comment by thaumanovic** [comment]
It seems that `init` properties are unsupported in this use case too.

I would be happy to submit a PR to change these if it would be accepted. Let me know. :)

**Comment by BlackWhiteYoshi** [comment]
If your condition is just the use of some older framework, I recommend to set the language version to 12 and also include [PolySharp](https://github.com/Sergio0694/PolySharp):


```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoInterface" Version="2.1.0" PrivateAssets="all" />
    <PackageReference Include="PolySharp" Version="1.14.1" PrivateAssets="all" />
  </ItemGroup>

</Project>
```

**Comment by thaumanovic** [comment]
This is something I considered, but the SDK we're writing is for our Unity frontend and we're reluctant to put things into what is an officially unsupported configuration.

**Comment by BlackWhiteYoshi** [comment]
yeah, Unity is known for being stone age, the target group for Unity are mostly beginner programmers. As experienced programmer it can be pretty rough to work with Unity, especially when it comes to language features and software architecture.

Give it a try. Set the language version to “latest” and see what you get. If you get C#12, Unity uses an up-to-date Roslyn compiler. Then try to compile and try to build a release version, if both works, you are good to go. The possibility of side effects is neglectable. I won’t they, they are impossible, but changing the language version is actually a pretty small and local change. The configuration affects only the compile process from your code to the IL assembly and everything beside that (other assemblies, linking of these assemblies, runtime) will be untouched.

PolySharp is even more harmless. It is just a source generator that creates some polyfill classes.

Regardless of the outcome, I already thought about the problem of language version compatibility. There was the decision between breaking everything down to version C#7.3 or just using the new features. I decided to just use the new features, because changing the language version is not a big deal.
