### ISSUE TITLE
Support Nested Interfaces

### ISSUE THREAD

**Issue by ristogod** [BlackWhiteYoshi/AutoInterface#4]
I have a pattern of nested interfaces repeated throughout many client implementations. However, I cannot seem to get AutoInterface to work with nested interfaces, despite my best efforts.

Here was the original interface and implementation:
Interface:
``` csharp
public interface IMonitorsClient
{
   #region properties

   IResponse AsResponse { get; }

   #endregion

   #region methods

   Task<string> GetAsync(CancellationToken cancellationToken = default);
   Task<string> GetAsync(Action<FlurlHttpSettings> withSettings, CancellationToken cancellationToken = default);

   #endregion

   #region nested types

   public interface IResponse
   {
      #region methods

      [MustDisposeResource] Task<IFlurlResponse> GetAsync(CancellationToken cancellationToken = default);
      [MustDisposeResource] Task<IFlurlResponse> GetAsync(Action<FlurlHttpSettings> withSettings, CancellationToken cancellationToken = default);

      #endregion
   }

   #endregion
}
```

Implementation:
``` csharp
public sealed class MonitorsClient(IClientFactory clientFactory) : ApiClientBase,
                                                                   IMonitorsClient
{
   #region properties

   public IMonitorsClient.IResponse AsResponse { get; } = new Response(clientFactory);

   #endregion

   #region methods

   public Task<string> GetAsync(CancellationToken cancellationToken = default) => GetAsync(WithSettingsDefault, cancellationToken);

   public Task<string> GetAsync(Action<FlurlHttpSettings> withSettings, CancellationToken cancellationToken = default) =>
      AsResponse.GetAsync(withSettings, cancellationToken)
                .ReceiveString();

   #endregion

   #region nested types

   sealed class Response : IMonitorsClient.IResponse
   {
      #region fields

      readonly IClientFactory _clientFactory;
      IFlurlClient?           _client;

      #endregion

      #region constructors

      internal Response(IClientFactory clientFactory) => _clientFactory = clientFactory;

      #endregion

      #region properties

      IFlurlClient Client => _client ??= _clientFactory.Get();

      #endregion

      #region methods

      [MustDisposeResource] public Task<IFlurlResponse> GetAsync(CancellationToken cancellationToken = default) => GetAsync(WithSettingsDefault, cancellationToken);

      [MustDisposeResource]
      public Task<IFlurlResponse> GetAsync(Action<FlurlHttpSettings> withSettings, CancellationToken cancellationToken = default) =>
         Client.Request("monitor")
               .WithSettings(withSettings)
               .GetAsync(cancellationToken: cancellationToken);

      #endregion
   }

   #endregion
}
```

Here is my attempt to recreate using AutoInterface:
``` csharp
[AutoInterface]
public sealed class MonitorsClient(IClientFactory clientFactory) : ApiClientBase,
                                                                   IMonitorsClient
{
   #region properties

   public IMonitorsClient.IResponse AsResponse { get; } = new Response(clientFactory);

   #endregion

   #region methods

   public Task<string> GetAsync(CancellationToken cancellationToken = default) => GetAsync(WithSettingsDefault, cancellationToken);

   public Task<string> GetAsync(Action<FlurlHttpSettings> withSettings, CancellationToken cancellationToken = default) =>
      AsResponse.GetAsync(withSettings, cancellationToken)
                .ReceiveString();

   #endregion

   #region nested types

   [AutoInterface]
   sealed class Response : IMonitorsClient.IResponse
   {
      #region fields

      readonly IClientFactory _clientFactory;
      IFlurlClient?           _client;

      #endregion

      #region constructors

      internal Response(IClientFactory clientFactory) => _clientFactory = clientFactory;

      #endregion

      #region properties

      IFlurlClient Client => _client ??= _clientFactory.Get();

      #endregion

      #region methods

      [MustDisposeResource] public Task<IFlurlResponse> GetAsync(CancellationToken cancellationToken = default) => GetAsync(WithSettingsDefault, cancellationToken);

      [MustDisposeResource]
      public Task<IFlurlResponse> GetAsync(Action<FlurlHttpSettings> withSettings, CancellationToken cancellationToken = default) =>
         Client.Request("monitor")
               .WithSettings(withSettings)
               .GetAsync(cancellationToken: cancellationToken);

      #endregion
   }

   #endregion
}
```

**Comment by BlackWhiteYoshi** [comment]
Nested Types decorated with [AutoInterface] will generate an interface, but the generated interface is always top-level. To generate nested interfaces is not supported and I will probably not implement support for it. I have 2 good reasons why it is problematic:

First of all you should know that every [AutoInterface] is independent from each other, so the inner [AutoInterface] does not know the outer [AutoInterface].
Then it is not obvious what the identifier of the outer type is. You expect “IMonitorsClient” as identifier and “IResponse” nested inside it. That makes sense, when both types have an [AutoInterface] and the default *Name*.
But what do you expect when MonitorsClient does not have an [AutoInterface]. Then “IMonitorsClient” never gets generated. Should “IResponse” then be nested inside “MonitorsClient” or still “IMonitorsClient”?
And what if the *Name* of the interface is set explicitly, so instead of “IMonitorsClient” you have “IMClient”, then you probably expect a nesting of “IMClient.IResponse”. But the [AutoInterface] are independent from each other, so “IResponse” does not know the *Name* for “MonitorsClient”.

Another problem is that since every generation is independent, the interface is generated at the [AutoInterface] of “MonitorsClient” and have to be declared again at the [AutoInterface] of “Respose” to nest “IResponse” inside “IMonitorsClient". So “IMonitorsClient” have to be marked as partial in both generations, what is also a bit ugly.

The second reason is that structuring with nested types is unusual. In my opinion (what is also considered as best practice) you should structure with namespaces and avoid nesting of types. Using nested types makes sense when you have a functional aspect e.g. you make the nested type private to make it an implementation detail of the outer type or the nested type needs access to a private member of the outer type.
Try to reconsider your structuring, maybe you come up with a solution that do not need nested interface types. A simple solution would be naming your interface type for the inner class “IMonitorsClientResponse”.

I hope you understand my thinking why I do not like this Idea.

**Comment by ristogod** [comment]
Yes, I understand. I do believe with enough construct, all of your concerns could be addressed.

The reason we arranged those particular interfaces in that manner is intentional. Within the namespace where we retain those clients, there maybe tens-hundreds of those clients, and having a consistent pattern of naming ensures productivity. And it largely stems from using off-shore resources, where they struggle to provide useful and meaningful names, and often name things with ever growing fantastical names simply chosen to avoid conflict and nothing else.

I do recognize that your proposed simple solution is reasonable, and I did consider it myself, but thought it was worth bring up for consideration. After all, when the interface is generated automatically and retained automatically, the name itself is inherently less important. The construct we use today is largely for human readability and comprehension and less so for anything else.

Thanks for the quick response.
