### ISSUE TITLE
Feature Request: Attribute Filtering

### ISSUE THREAD

**Issue by ristogod** [BlackWhiteYoshi/AutoInterface#9]
Recently attributes found on the implementation class were persisted to the generated interface as covered in issue #3 .

This change was a welcomed change and received well as the default use-case, and I appreciate you fulfilling this request.

However, a coworker pointed out a scenario when used with another [code generating package](https://github.com/riok/mapperly), where the attributes there exist to drive behavior within the generated mapper.

``` csharp
namespace MyApp;

[AutoInterface]
[Mapper(EnumMappingStrategy = ByName, UseReferenceHandling = true)]
public sealed partial class Mapper : IMapper
{
   [MapperIgnoreSource(nameof(Data.FilterCategory.CreatedTs))]
   [MapperIgnoreSource(nameof(Data.FilterCategory.LastUpdatedTs))]
   [MapperIgnoreTarget(nameof(Services.FilterCategory.ChildFilterCategory))]
   [MapProperty([nameof(Data.FilterCategory.ColorFilterCategory), nameof(Data.FilterCategory.ColorFilterCategory.Hex)], [nameof(Services.FilterCategory.Hex)])]
   public partial Services.FilterCategory MapFrom(Data.FilterCategory source);
}
```

Generates:
``` csharp
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace MyApp;

public interface IMapper {
   [MapperIgnoreSource(nameof(Data.FilterCategory.CreatedTs))]
   [MapperIgnoreSource(nameof(Data.FilterCategory.LastUpdatedTs))]
   [MapperIgnoreTarget(nameof(Services.FilterCategory.ChildFilterCategory))]
   [MapProperty([nameof(Data.FilterCategory.ColorFilterCategory), nameof(Data.FilterCategory.ColorFilterCategory.Hex)], [nameof(Services.FilterCategory.Hex)])]
   Services.FilterCategory MapFrom(Data.FilterCategory source);
}
```

I am not opinionated on whether those attributes are persisted to the interface as there doesn't appear to be any obvious concerns. However, we have observed odd behavior with the mapper logic itself for some generated maps with the addition of AutoInterface. Although we haven't pin-pointed the exact cause, it does appear that when we declare the interface ourselves, omitting the corresponding attributes, we observe the expected behavior of the mapper.

The actual mapper in question is vast and we had hoped to leverage AutoInterface for code maintainability purposes, keeping our implementation and contracts in sync.

Ideally, for some distinct scenarios, it might be beneficial to control which attributes are filtered out of the interface.

A suggested approach:

``` csharp
namespace MyApp;

[AutoInterface(ExcludeAttributes = [typeof(MapperIgnoreSource), typeof(MapperIgnoreTarget), typeof(MapProperty)])]
[Mapper(EnumMappingStrategy = ByName, UseReferenceHandling = true)]
public sealed partial class Mapper : IMapper
{
   [MapperIgnoreSource(nameof(Data.FilterCategory.CreatedTs))]
   [MapperIgnoreSource(nameof(Data.FilterCategory.LastUpdatedTs))]
   [MapperIgnoreTarget(nameof(Services.FilterCategory.ChildFilterCategory))]
   [MapProperty([nameof(Data.FilterCategory.ColorFilterCategory), nameof(Data.FilterCategory.ColorFilterCategory.Hex)], [nameof(Services.FilterCategory.Hex)])]
   public partial Services.FilterCategory MapFrom(Data.FilterCategory source);
}
```

Perhaps there are use-case scenarios where more granular control could be needed, but I thought a simple start might suffice.

Thanks for your consideration.

**Comment by BlackWhiteYoshi** [comment]
It is unlikely that the generated attributes of *AutoInterface* influence the generation of *Mapperly*, because source generators are independent from each other. Each source generator gets as input the source code before any generation. A source generator cannot see the output of another generator, so for *Mapperly* the generated interfaces does not exist.

Maybe the problem is exactly that: Somewhere *Mapperly* needs to read an interface, but the interface is not present because it will be generated by *AutoInterface* and *Mapperly* is not able to see it. And when the interface is created manually, *Mapperly* has no problems finding the interface.

Another thing that is possible is when working with multiple *.csproj*/assemblies. When code is generated in the first *.csproj* and the second *.csproj* has a reference on the first *.csproj*, then the generated code of the first *.csproj* is visible for the generators of the second *.csproj*.
In this case the generated attributes of *AutoInterface* are visible to *Mapperly*, but the [Mapper]-attribute is not present at the interface, so it should not affect anything.

I want to wait until you pin-point the exact cause before making a decision, because I still think that the attributes do not harm and the cases they do harm are so rare, that this feature is not worth it.

In case you do not know, you can use *&lt;EmitCompilerGeneratedFiles&gt;true&lt;/EmitCompilerGeneratedFiles&gt;* to save the generated source code to disk.
Good Luck

**Comment by ristogod** [comment]
The team was able to reproduce the bug without AutoInterface involved at all. So their initial assumptions were incorrect and therefore this feature request should not be needed. Thanks for the consideration.
